/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     MAP = {16b0,16b0,16b0,16b1111,16b0,16b0,16b1001,16b1110,16b0,16b1011,16b0,16b0,16b0101,16b0110,16b0,16b0}
*/
module joystick_mapper_21 (
    input [3:0] map_in,
    output reg [15:0] map_out
  );
  
  localparam MAP = 256'h000000000000000f000000000009000e0000000b000000000005000600000000;
  
  
  always @* begin
    map_out = MAP[(map_in)*16+15-:16];
  end
endmodule
